wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>",views.entry, name="entry"),
    path("newpage",views.newpage, name="newpage"),
    path("wiki/<str:entry>/editpage", views.edit,name="edit" ),
    path("random",views.random,name = "random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from markdown2 import Markdown
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms
from . import util

class Newformnewpage(forms.Form):
    editform = forms.BooleanField(initial=False,widget=forms.HiddenInput(),required=False)
    title = forms.CharField(label="Entry",widget=forms.TextInput(attrs={'class' : 'form-control col-md-6'}))
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={'class' : 'form-control col-md-6'}))

def index(request):
    if request.method == "POST":
        search_item = request.POST.get("q")
        if(util.get_entry(search_item) is not None):
            return entry(request,search_item)
        else:
            search_list=[]
            for en in util.list_entries():
                if search_item.lower() in en.lower():
                    search_list.append(en)
            return render(request, "encyclopedia/index.html", {
                "entries": search_list
                })

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request,entry):
    file = util.get_entry(entry)
    M=Markdown()
    if file is None:
        return render(request,"encyclopedia/notfound.html")
    else:
        return render(request,"encyclopedia/All_entry.html",{
            "content":M.convert(file),
            "name":entry
        })


def newpage(request):
    Flag = False
    if request.method == "POST":
        data = Newformnewpage(request.POST)
        if data.is_valid():
            title_data = data.cleaned_data["title"]
            content_data = data.cleaned_data["content"]
            if util.get_entry(title_data) is None or data.cleaned_data["editform"]:
                util.save_entry(title_data, content_data)
                return entry(request,title_data)
            else:
                Flag = True
                return render(request, "encyclopedia/newpage.html", {
                    "form":data,
                    "Flag":Flag,
                    "entry":title_data,
                    "edit": False
                })
        else:
            Flag = True
            return render(request, "encyclopedia/newpage.html", {
                "form": data,
                "Flag": Flag,
                "entry": data.cleaned_data["title"],
                "edit":False
            })


    return render(request, "encyclopedia/newpage.html" ,{
        "form":Newformnewpage() ,
        "Flag":Flag
    })

def edit(request, entry):
    if util.get_entry(entry) is None:
        return render(request, "encyclopedia/notfound.html")
    else:
        F = Newformnewpage()
        F.fields["title"].initial = entry
        F.fields["title"].widget = forms.HiddenInput()
        F.fields["content"].initial = util.get_entry(entry)
        F.fields["editform"].initial = True
        return render(request,"encyclopedia/newpage.html",{
            "form":F,
            "Flag":False,
            "edit":True,
            "entry": entry
        })

def random(request):
    from random import randint
    all_entry = util.list_entries()
    entry = randint(0,len(all_entry)-1)
    return HttpResponseRedirect(reverse("wiki:entry", kwargs= {'entry' : all_entry[entry]}))

wiki/encyclopedia/templates/encyclopedia/ALL_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{name}}
{% endblock %}

{% block body %}
    {{ content | safe }}
    <button><a href="/wiki/{{ name }}/editpage">Edit</a> </button>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="/wiki/{{ entry }} "> <li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href = "{% url 'wiki:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    {% if Flag %}
        <h1> Error : SV009 - Entry With the same name exist. </h1>
        <h6><a href="/wiki/{{ entry }}/editpage">Edit</a> : {{entry}}</h6>
    {% elif edit %}
        <h1> Edit Page : {{ entry }}</h1>
    {% else %}
        <h2> Make a new entry in Domain</h2>
    {% endif %}
    <div class="form-group">
        <form action="{% url 'wiki:newpage' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn btn-primary" style="margin-top :10px ">
        </form>
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/notfound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h3> Error 404 : Page not found. </h3>
{% endblock %}